#!/bin/bash
set -a

export DISCO=$(cd `dirname $0/`/../; pwd)
echo -e "\nIt seems that Disco is at $DISCO"

DISCO_CONF=${1:-"$DISCO/conf/disco.conf.dev-example"}
LIGHTTPD_CONF=${2:-"$DISCO/conf/lighttpd-master.conf"}

echo "Disco config is at $DISCO_CONF"
echo "Lighttpd config is at $LIGHTTPD_CONF"
echo -e "\nIf this is not what you want, run start-master as follows:"
echo -e "start-master [disco-config] [lighttpd-config]\n"

source $DISCO_CONF
export PATH=$PATH:/usr/sbin
export PYTHONPATH=$PYTHONPATH:$DISCO/node:$DISCO/pydisco

$DISCO_HOME/disco-master &

if lighttpd -f $LIGHTTPD_CONF; then
	echo -e "\nLighttpd for Disco master started.\n"
else
	echo -e "\nLighttpd for Disco master didn't start.\n"
fi

