#!/usr/bin/env python
import sys
from os import environ, listdir
from os.path import join, basename, abspath
from disco.ddfs import DDFS
from optparse import OptionParser

parser = OptionParser(usage = 'usage: %prog [options] directory [ddfs-host]')
parser.add_option('-t', '--tag', default='',
    help='Tag name (default: directory name)')

(options, args) = parser.parse_args()
host = args[1] if len(args) > 1 else environ.get('DDFS_HOST', None)
if not (args and host):
    parser.print_help()
    sys.exit(1)

ddfs = DDFS(host)
dir = args[0]
tag = parser.values.tag
tag = tag if tag else "data:" + DDFS.safe_name(basename(abspath(dir)))

blobs = [join(dir, p) for p in listdir(dir)]
print "Pushing %d blobs at '%s' under tag '%s'." % (len(blobs), dir, tag)
ddfs.push(tag, blobs)
print "ok"
