#!/usr/bin/env python
import sys
import subprocess
from os import environ
from disco.ddfs import DDFS
from disco.error import CommError
from disco.util import urlresolve

if 'DDFS_HOST' not in environ or len(sys.argv) != 2:
    print >> sys.stderr, "Usage: ddfs-cat <tag>"
    print >> sys.stderr, "       Print all blobs reachable from tag to stdout"
    print >> sys.stderr, "Requires DDFS_HOST=disco://<hostname> environment variable"
    sys.exit(1)

tag = sys.argv[1]
ddfs = DDFS(environ['DDFS_HOST'])

try:
    blobs=ddfs.blobs(tag)
except CommError, x:
    if x.code == 404:
        print >>sys.stderr, "Tag not found: %s"%tag
        sys.exit(1) # no such tag
    raise

def cat(replicas):
    for r in replicas:
        if subprocess.call(['wget' ,'-q', '-O-', r])==0:
            return
    print >>sys.stderr, "Failed downloading all replicas:", replicas
    sys.exit(1)
    
for blob in blobs:
    blob=[urlresolve(r) for r in blob]
    cat(blob)
