#!/usr/bin/env python
import sys
from os import environ
from disco.ddfs import DDFS
from disco.error import CommError

if 'DDFS_HOST' not in environ or len(sys.argv) != 2:
    print >> sys.stderr, "Usage: ddfs-rm <tag>"
    print >> sys.stderr, "       Remove given tag"
    print >> sys.stderr, "       ddfs-rm <prefix>*"
    print >> sys.stderr, "       Remove all tags starting with prefix"
    print >> sys.stderr, "Requires DDFS_HOST=disco://<hostname> environment variable"
    sys.exit(1)

tag = sys.argv[1]
ddfs = DDFS(environ['DDFS_HOST'])
if tag.endswith('*'):
    for tag in ddfs.list(tag[:-1]):
        ddfs.delete(tag)
else:
    try:
        ddfs.delete(tag)
    except CommError, x:
        if x.code == 404:
            print >>sys.stderr, "Tag not found:", tag
            sys.exit(1)
        raise
