#!/usr/bin/env python
import sys
from os import environ, listdir
from os.path import join, basename, abspath
from disco.ddfs import DDFS

if len(sys.argv) < 2 or ('DDFS_HOST' not in environ and len(sys.argv) < 4):
    print >> sys.stderr, "Usage: ddfs-pushdir dir [tag] [ddfs_host]"
    print >> sys.stderr, "       or specify DDFS_HOST"
    sys.exit(1)

host = environ['DDFS_HOST'] if 'DDFS_HOST' in environ else sys.argv[3]
ddfs = DDFS(host)
dir = sys.argv[1]
tag = ddfs.safe_name(sys.argv[2] if len(sys.argv) > 2
                                 else "data:" + basename(abspath(dir)))

blobs = [join(dir, p) for p in listdir(dir)]
print "Pushing %d blobs at '%s' under tag '%s'." % (len(blobs), dir, tag)
ddfs.push(tag, blobs)
print "ok"
