#!/usr/bin/env python
import sys
from os import environ
from disco.ddfs import DDFS
from disco.util import flatten
from disco.error import CommError

if len(sys.argv) < 2 or ('DDFS_HOST' not in environ and len(sys.argv) < 3):
    print >> sys.stderr, "Usage: ddfs-blobs tag [ddfs_host]"
    print >> sys.stderr, "       or specify DDFS_HOST"
    sys.exit(1)

host = environ['DDFS_HOST'] if 'DDFS_HOST' in environ else sys.argv[2]
ddfs = DDFS(host)

try:
    for url in flatten(ddfs.blobs(sys.argv[1])):
        print url.split('/')[-1], url
except CommError, x:
    if x.code == 404:
        print >> sys.stderr, "Tag not found"
    else:
        raise
