#!/usr/bin/env python

import sys
from disco import util
from disco.comm import download

for url in sys.argv[1:]:
        for u in util.urllist(url):
                if u.startswith("disco://"):
                        host, fname = u[8:].split("/", 1)
                        u = util.proxy_url(fname, host)
                print download(u)


