#!/bin/bash

# Basic settings

DISCO_SCGI_PORT=${DISCO_SCGI_PORT:-"4444"}
DISCO_ROOT=${DISCO_ROOT:-"/srv/disco/"}
DISCO_HOME=${DISCO_HOME:-"/usr/lib/disco/"}
DISCO_LOG=${DISCO_LOG:-"/var/log/disco/"}
DISCO_ULIMIT=${DISCO_ULIMIT:-"16000000"}
DISCO_PID_DIR=${DISCO_PID_DIR:-"/var/run/"}
DISCO_MASTER_HOST=${DISCO_MASTER_HOST:-""}
DISCO_SLAVES_OS=${DISCO_SLAVES_OS:-"linux"}

# Derived settings

DISCO_NAME=${DISCO_NAME:-"disco_$DISCO_SCGI_PORT"}
DISCO_DATA=${DISCO_DATA:-"$DISCO_ROOT/data"}
DISCO_LOCALDIR=${DISCO_LOCALDIR:-"$DISCO_ROOT/local/_$DISCO_NAME"}
DISCO_MASTER=${DISCO_MASTER:-"$DISCO_DATA/_$DISCO_NAME"}
DISCO_CONFIG=${DISCO_CONFIG:-"$DISCO_ROOT/$DISCO_NAME.config"}
DISCO_MASTER_LOG=${DISCO_MASTER_LOG:-"$DISCO_LOG/$DISCO_NAME.log"}

if [ ! -e $DISCO_MASTER ] && ! mkdir -p $DISCO_MASTER; then
	echo "$DISCO_MASTER doesn't exist"
	exit 1
fi

if [ ! -e $DISCO_LOCALDIR ] && ! mkdir -p $DISCO_LOCALDIR; then
	echo "$DISCO_LOCALDIR doesn't exist"
	exit 1
fi

echo "Using master... $DISCO_MASTER"
echo "Using slaves with... $DISCO_SLAVES_OS"
[ -z $DISCO_MASTER_HOST ] || echo "Using master host... $DISCO_MASTER_HOST"

if [ ! -e $DISCO_CONFIG ] && ! echo "[]" > $DISCO_CONFIG; then
        echo "Couldn't initialize $DISCO_CONFIG"
        exit 1
fi
echo "Using config... $DISCO_CONFIG"

# If DISCO_HEART is not specified, HEART_COMMAND is empty and heart
# will die togehter with the master process.
export HEART_COMMAND=${DISCO_HEART:+"$0 $@"}

export DISCO_PID_FILE=$DISCO_PID_DIR"/disco-master.pid"

PID=$(cat $DISCO_PID_FILE 2>/dev/null)

if [ $PID ] && [ -d "/proc/$PID" ]; then
        echo "Disco master seems to be running already (PID $PID)."
        exit 1
fi

# Prevent disasterous memory leaks from trashing the server
ulimit -v $DISCO_ULIMIT 2>/dev/null

erl +K true\
    -heart\
    -detached\
    -sname $DISCO_NAME"_master"\
    -rsh ssh\
    -connect_all false\
    -pa "$DISCO_HOME/ebin"\
    -kernel error_logger "{file, \"$DISCO_MASTER_LOG\"}"\
    -disco disco_name \"$DISCO_NAME\"\
    -disco disco_root \"$DISCO_MASTER\"\
    -disco disco_localdir \"$DISCO_LOCALDIR\"\
    -disco disco_master_host \"$DISCO_MASTER_HOST\"\
    -disco disco_slaves_os \"$DISCO_SLAVES_OS\"\
    -disco scgi_port $DISCO_SCGI_PORT\
    -disco disco_config \"$DISCO_CONFIG\"\
    -eval "[handle_job, handle_ctrl]"\
    -eval "application:start(disco)" </dev/null >/dev/null 2>/dev/null

sleep 1

NPID=$(cat $DISCO_PID_FILE 2>/dev/null)

if [ -z $NPID ] || [ ! -d "/proc/$NPID" ]; then
        echo "Starting Disco master failed."
        echo "See the log file at $DISCO_MASTER_LOG for more information."
        exit 1
fi


