#!/bin/bash

# Basic settings

DISCO_SCGI_PORT=${DISCO_SCGI_PORT:-"4444"}
DISCO_ROOT=${DISCO_ROOT:-"/srv/disco/"}
DISCO_HOME=${DISCO_HOME:-"/usr/lib/disco/"}
DISCO_LOG=${DISCO_LOG:-"/var/log/disco/"}
DISCO_ULIMIT=${DISCO_ULIMIT:-"16000000"}
DISCO_PID_DIR=${DISCO_PID_DIR:-"/var/run/"}

# Derived settings

DISCO_NAME=${DISCO_NAME:-"disco_$DISCO_SCGI_PORT"}
DISCO_DATA=${DISCO_DATA:-"$DISCO_ROOT/data"}
DISCO_MASTER=${DISCO_MASTER:-"$DISCO_DATA/_$DISCO_NAME"}
DISCO_CONFIG=${DISCO_CONFIG:-"$DISCO_ROOT/$DISCO_NAME.config"}
DISCO_MASTER_LOG=${DISCO_MASTER_LOG:-"$DISCO_LOG/$DISCO_NAME.log"}

if [ ! -e $DISCO_MASTER ] && ! mkdir -p $DISCO_MASTER; then
	echo "$DISCO_MASTER doesn't exist"
	exit 1
fi

if [ ! -e $DISCO_CONFIG ] && ! echo "[]" > $DISCO_CONFIG; then
        echo "Couldn't initialize $DISCO_CONFIG"
        exit 1
fi


# If DISCO_HEART is not specified, HEART_COMMAND is empty and heart
# will die togehter with the master process.
export HEART_COMMAND=${DISCO_HEART:+"$0 $@"}

# Prevent disasterous memory leaks from trashing the server
ulimit -v $DISCO_ULIMIT

erl +K true\
    -heart\
    -noshell\
    -sname $DISCO_NAME"_master"\
    -rsh ssh\
    -pa "$DISCO_HOME/ebin"\
    -boot "$DISCO_HOME/disco"\
    -kernel error_logger "{file, \"$DISCO_MASTER_LOG\"}"\
    -eval "[handle_job, handle_ctrl]"\
    -disco disco_name \"$DISCO_NAME\"\
    -disco disco_root \"$DISCO_MASTER\"\
    -disco scgi_port $DISCO_SCGI_PORT\
    -disco disco_config \"$DISCO_CONFIG\" &

echo "$!" > $DISCO_PID_DIR"/disco-master.pid"

