#!/bin/bash

src=../src

if [ `uname` == "Darwin" ]; then
    FLAGS="-O3 -fnested-functions"
else
#    FLAGS="-DHUFFMAN_DEBUG"
    FLAGS="-O3"
fi

gcc -g -Wall -I $src $FLAGS -c \
    $src/ddb*.c \
    $src/util.c
gcc -g -Wall -I $src $FLAGS -o create_discodb -lcmph \
    create_discodb.c \
    *.o
gcc -g -Wall -I $src $FLAGS -o query_discodb  -lcmph \
    query_discodb.c \
    *.o
